### ISSUE TITLE
cannot use kmeans_cuda in pipeline.py

### ISSUE THREAD

**Issue by jamesuperboy** [kasiv008/OFFSEG#2]
Traceback (most recent call last):
  File "pipeline.py", line 169, in <module>
    msk_img,predicts= col_seg(image,pool,model)
  File "pipeline.py", line 135, in col_seg
    msk_img=palette_lst(travcut)
  File "pipeline.py", line 54, in palette_lst
    palette, data['Cluster']= kmeans_cuda(data, n_classes, verbosity=1, seed=1)
ValueError: the number of features must be even in fp16 mode

The bug is above. I have seen the feature of the data(shape: n*3) is 3, so how to solve this problem?

**Comment by zj010131** [comment]
I have encountered the same problem as you. Have you resolved it？

**Comment by kasiv008** [comment]
I have updated the code to use fast_pytorch_kmeans. please use this one.
